app:
  host : localhost:8080
  origin: http://localhost:4200,http://localhost:4201

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/projectcafe
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: 0a29ca69b3583e
    password: ae017039a74075
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true	
 
server:
  port: 8080
logging:
  level:
    root: INFO
    com.project.cafe: DEBUG
   
 
